# Generated by Django 5.0.7 on 2024-08-03 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Advertisement campaign name')),
                ('promotion_channel', models.CharField(max_length=200, verbose_name='Promotion channel')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Advertisement budget')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='products.product', verbose_name='Product to be promoted')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
