# Generated by Django 5.0.7 on 2024-08-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.TextField(blank=True, verbose_name='Service description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Service price')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
