# Generated by Django 5.0.7 on 2024-08-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='contracts.contract', verbose_name='Contract')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
