# Generated by Django 5.0.7 on 2024-08-03 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
