# Generated by Django 5.0.7 on 2024-08-01 00:21

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('contract_file', models.FileField(upload_to=pathlib.PureWindowsPath('D:/coding/works/django_crm_system_skillbox/crm_system/media'), verbose_name='Contract file')),
                ('start_date', models.DateTimeField(verbose_name='Contract singing date')),
                ('end_date', models.DateTimeField(verbose_name='Contract expire date')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
